# Generated by Django 4.2.3 on 2023-07-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('salario_base', models.FloatField()),
                ('horas_trabajadas', models.FloatField()),
                ('dpi', models.CharField(max_length=13)),
                ('genero', models.SmallIntegerField(choices=[(1, 'MASCULINO'), (2, 'FEMENINO'), (3, 'OTRO')])),
            ],
        ),
    ]
